CREATE DATABASE rathena; 
CREATE USER rathena@localhost IDENTIFIED BY 't-?*Mvb5~yD+]a=Z';
GRANT ALL PRIVILEGES ON rathena.* to rathena@localhost IDENTIFIED BY 't-?*Mvb5~yD+]a=Z';
flush privileges;
USE rathena;
source /usr/bin/rathena/sql-files/main.sql;
source /usr/bin/rathena/sql-files/logs.sql;
source /usr/bin/rathena/sql-files/item_db.sql;
source /usr/bin/rathena/sql-files/item_db_re.sql;
source /usr/bin/rathena/sql-files/item_db2.sql;
source /usr/bin/rathena/sql-files/item_db2_re.sql;
source /usr/bin/rathena/sql-files/item_cash_db.sql;
source /usr/bin/rathena/sql-files/item_cash_db2.sql;
source /usr/bin/rathena/sql-files/mob_db.sql;
source /usr/bin/rathena/sql-files/mob_db2.sql;
source /usr/bin/rathena/sql-files/mob_db2_re.sql;
source /usr/bin/rathena/sql-files/mob_db_re.sql;
source /usr/bin/rathena/sql-files/mob_skill_db.sql;
source /usr/bin/rathena/sql-files/mob_skill_db2.sql;
source /usr/bin/rathena/sql-files/mob_skill_db_re.sql;
source /usr/bin/rathena/sql-files/mob_skill_db2_re.sql;
